### ISSUE TITLE
Test /dev/shm sustained write performance

### ISSUE THREAD

**Issue by coretl** [DiamondLightSource/dev-shm-tests#1]
The steps:
- Read chunks from and HDF file
- Write chunks as separate files to /dev/shm
- Have something delete those chunks so we keep /dev/shm filled to a reasonable level
- Measure write performance
- Continue for a long time
- Measure write performance again
- Write down the results in a short report listing test conditions
- If performance shows any slowdown, repeat but using one big file in /dev/shm as a circular buffer
- Ask Graeme for further details

**Comment by coretl** [comment]
~~@evalott100 I can't seem to assign you to this ticket~~

Had to add people individually to the repo, now I am able to assign you...

**Comment by coretl** [comment]
@graeme-winter here's the repo we can put the script in

**Comment by graeme-winter** [comment]
I shall annotate

Thank you

**Comment by evvaaaa** [comment]
Starting to take a look at this now.

**Comment by graeme-winter** [comment]
We annotated earlier _via_ white board

In response to a request for example data: several hefty examples at e.g. 

```
/dls/i04-1/data/2021/cm28181-3/gw/20210720/TestInsulin/Insulin_12/Insulin_12_1*h5
```

etc.

**Comment by evvaaaa** [comment]
Here's a link to the written report
https://confluence.diamond.ac.uk/x/_6WZCQ

**Comment by coretl** [comment]
Initial phase done, will open another ticket for additional work later
